### ISSUE TITLE
Changing the project title

### ISSUE THREAD

**Issue by stack72** [damianh/ProxyKit#10]
After a straw poll at #flashcon, we’ve decided that we believe that the project name doesn’t reflect the ability of the project 

Therefore, we need to track a motion to rename

**Comment by thefringeninja** [comment]
Dotnet Extensible Reverse Proxy sounds good

**Comment by JoeStead** [comment]
I wish I booked a flight 😂

**Comment by thefringeninja** [comment]
PS not renaming this: https://github.com/thefringeninja/Derp.Inventory

**Comment by damianh** [comment]
I agonized over this... I mean, who _doesn't_ want to do `dotnet add package Derp`?? In fact, isn't that what we do **every day**.

However, in order to not jeopardize my future MVP award for open source contributions to a healthy dotnet OSS community and general all round Corporate / Enterprise / OSS Sponsor acceptance I must decline your valuable suggestions (except for your @jchannon, that one sucked).

I know that one day we will look back at this as an 'opportunity lost' or 'the package that got away'; I will have to live with the consequence of my decision. 

With a heavy :heart:, Damian
