### ISSUE TITLE
Google Drive video playback

### ISSUE THREAD

**Issue by ryanjerskine** [damianh/ProxyKit#93]
I am wanting to use this project to 'proxy' video playback to Google Drive. An example of the code I am currently using:

```
[HttpGet("{id}")]
[Authorize]
public async Task<IActionResult> GetAsync([FromRoute] string id, [FromQuery] int? quality)
{
    HttpResponseMessage result = null;
    using (var httpClient = new HttpClient())
    {
        httpClient.DefaultRequestHeaders.Authorization = await this._TokenManager.GetGoogleDriveAuthHeaderAsync();
        result = await httpClient.GetAsync($"https://drive.google.com/get_video_info?docid={id}");
        var actualResult = await result.Content.ReadAsStringAsync();
        var videoInfo = this._VideoInfoParser.Parse(actualResult);
        var q = videoInfo.maps.Where(m => m.quality == "medium").FirstOrDefault();
        return new FileStreamResult(await httpClient.GetStreamAsync(q.url), "video/mp4");
    }
}
```

Is there a way to do this with ProxyKit or do I need to look for another solution?

**Comment by damianh** [comment]
Firstly, I think your solution is fine and you don't need to seek another. The only thing I would suggest is that you use HttpClientFactory instead of new-ing up your own instance. 

Separately I have been thinking about proxykit supporting paramaterised routes, but that will be a future version. I'm closing this because I honestly think your solution is fine.
